### ISSUE TITLE
CI failure on Windows 10 / Python 3.9.10

### ISSUE THREAD

**Issue by sio** [sio/Makefile.venv#17]
Scheduled test runs have started failing today on `windows-latest`:

#### First failure: https://github.com/sio/Makefile.venv/runs/5257374669?check_suite_focus=true
  This run was using:
```
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.20348-SP0
GNU Make 4.2.1
```

#### Previous successful run on the same codebase: https://github.com/sio/Makefile.venv/runs/5121494065?check_suite_focus=true
  This run was using:
```
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Windows-10-10.0.17763-SP0
GNU Make 4.2.1
```

#### Probable reasons for failure

The obvious change in CI runner is Python upgrade from 3.7.9 to 3.9.10. The failure is not inherent to that Python version: macos and cygwin were already using it successfully in the same run.

Rerun eliminated test failures related to command timeouts, but this one has remained:

```
FAIL: test_setup_cfg (tests.test_dependencies.TestDependencies)
Check that setup.cfg is being processed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\Makefile.venv\Makefile.venv\tests\test_dependencies.py", line 33, in test_setup_cfg
    make = self.make('hello', makefile=makefile)
  File "D:\a\Makefile.venv\Makefile.venv\tests\common.py", line 62, in make
    self.check_returncode(process, returncode)
  File "D:\a\Makefile.venv\Makefile.venv\tests\common.py", line 67, in check_returncode
    self.assertEqual(
AssertionError: 2 != 0 : make exited with code 2 (expected 0)

stdout:
mingw32-make[1]: Entering directory 'C:/Users/RUNNER~1/AppData/Local/Temp/Makefile.venv_test_7o0hpfn3'
./.venv/Scripts/pip install -e ./
Obtaining file:///C:/Users/RUNNER~1/AppData/Local/Temp/Makefile.venv_test_7o0hpfn3
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pyfiglet in c:\users\runneradmin\appdata\local\temp\makefile.venv_test_7o0hpfn3\.venv\lib\site-packages (from hello==0.0.0) (0.8.post1)
Installing collected packages: hello
  Attempting uninstall: hello
    Found existing installation: hello 0.0.0
mingw32-make[1]: Leaving directory 'C:/Users/RUNNER~1/AppData/Local/Temp/Makefile.venv_test_7o0hpfn3'

stderr:
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Makefile.venv_test_7o0hpfn3\.venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Makefile.venv_test_7o0hpfn3\.venv\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Makefile.venv_test_7o0hpfn3\.venv\lib\site-packages\pip\_internal\commands\install.py", line 405, in run
    installed = install_given_reqs(
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Makefile.venv_test_7o0hpfn3\.venv\lib\site-packages\pip\_internal\req\__init__.py", line 68, in install_given_reqs
    uninstalled_pathset = requirement.uninstall(auto_confirm=True)
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Makefile.venv_test_7o0hpfn3\.venv\lib\site-packages\pip\_internal\req\req_install.py", line 637, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "C:\Users\RUNNER~1\AppData\Local\Temp\Makefile.venv_test_7o0hpfn3\.venv\lib\site-packages\pip\_internal\req\req_uninstall.py", line 530, in from_dist
    assert link_pointer == dist_location, (
AssertionError: Egg-link c:\users\runner~1\appdata\local\temp\makefile.venv_test_7o0hpfn3 does not match installed location of hello (at c:\users\runneradmin\appdata\local\temp\makefile.venv_test_7o0hpfn3)
mingw32-make[1]: *** [D:\a\Makefile.venv\Makefile.venv\Makefile.venv:223: .venv/Scripts/.initialized-with-Makefile.venv] Error 2
```

The last part indicates that the issue is caused by pip failing to correctly compare shortened Windo~1 path to a full version:

```
AssertionError: 
Egg-link c:\users\runner~1\appdata\local\temp\makefile.venv_test_7o0hpfn3 
does not match installed location of hello 
(at c:\users\runneradmin\appdata\local\temp\makefile.venv_test_7o0hpfn3)
```

I'll wait this out a little in hopes that upstream pip will fix the issue in the next update. Will check pip bug reports now.

**Comment by sio** [comment]
Related upstream issues:

- Similar, but not quite the same: https://github.com/pypa/pip/issues/10696
- This PR should fix our issue (when merged): https://github.com/pypa/pip/pull/10697

**Comment by sio** [comment]
[Upstream PR](https://github.com/pypa/pip/pull/10697) was just merged, and this issue should not occur with `pip>22.0.3`. [It seems though](https://pip.pypa.io/en/latest/development/release-process/) that next release will happen only in April. In the meantime we will avoid using default Windows temporary directory and will create another one with a shorter name:

https://github.com/sio/Makefile.venv/blob/0ad1b47079cd06fec5d6a3ff13a5531a8847c30f/.github/workflows/test.yml#L36-L37

This workaround will become unnecessary after the next pip release and should be removed prior to closing this issue.

**Comment by sio** [comment]
Even though pip version has been released with a fix, I don't feel comfortable removing this workaround. This is Windows after all. It can always find another way to choke on a filepath.

I'm closing this issue now.
